#!/bin/bash

set -euo pipefail

echo "$FLUTTER_WEATHER_KEYSTORE" > "$FLUTTER_WEATHER_KEYSTORE_JKS_ASC_FILE_PATH"
gpg -d --passphrase "$FLUTTER_WEATHER_KEYSTORE_PASS" --batch "$FLUTTER_WEATHER_KEYSTORE_JKS_ASC_FILE_PATH"> "$FLUTTER_WEATHER_KEYSTORE_JKS_FILE_PATH"