platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'Runner' do
  use_frameworks!
  pod 'Firebase/Analytics', :modular_headers => true
  pod 'Firebase/Core', :modular_headers => true
end