version: '3'
services:
  flutter_weather_dev:
    container_name: flutter_weather_dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '$PWD:/home/developer/workspace'
      - '/dev/bus/usb:/dev/bus/usb'
    privileged: true
    stdin_open: true
    tty: true
    command: flutter run -t lib/main_dev.dart --flavor dev

  flutter_weather_prod:
    container_name: flutter_weather_prod
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '$PWD:/home/developer/workspace'
      - '/dev/bus/usb:/dev/bus/usb'
    privileged: true
    stdin_open: true
    tty: true
    command: flutter run -t lib/main_prod.dart --flavor prod --release
