name: "Firebase Remote Configuration Test"

on:
  push: 
    branches: 
      - feature-version-check

jobs: 
  version:
    name: "Generate Version Number"
    runs-on: ubuntu-latest
    env:
      VERSION_TXT_PATH: ${{ './apps/mobile_flutter/version.txt' }}
    steps:
      - 
        uses: actions/checkout@v2
      - 
        name: "Fetch all history for all tags and branches"
        run: git fetch --unshallow
      - 
        name: "Install GitVersion"
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
            versionSpec: '5.x'
      - 
        name: "Use GitVersion"
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: ./git-version.yml
      - 
        name: "Create version.txt"
        run: echo "${{ steps.gitversion.outputs.NuGetVersion }}+${{ github.run_id }}" > "${{ env.VERSION_TXT_PATH }}"
      - 
        name: "Upload version.txt"
        uses: actions/upload-artifact@v2
        with:
          name: gitversion
          path: "${{ env.VERSION_TXT_PATH }}"

  build: 
    name: "TEST"
    needs: [ version ]
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        uses: actions/setup-java@v1
        with: 
          java-version: 12.x
      - 
        name: "Download firebase remote configuration"
        uses: ridermansb/firebase-action@master
        with:
          args: remoteconfig:get -o .github/templates/firebase-remote-config.json
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      - 
        name: "Update firebase remote configuration"
        run: exec .github/scripts/update-remote-config.sh -p android -v "${{ steps.version.outputs.content }}"
      - 
        name: "Deploy firebase remote configuration"
        uses: ridermansb/firebase-action@master
        with:
          args: deploy --only remoteconfig
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}